/*
data = [
{x: 1, y:1, beacons: [{bid: 1, rssi: 0}, {}]},
];
*/
var accessPoint =
[
   {
      "x":156,
      "y":40,
      "beacons":[
         {
            "bid":1,
            "rssi":-80
         },
         {
            "bid":2,
            "rssi":-84
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-73
         },
         {
            "bid":5,
            "rssi":-85
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":156,
      "y":40,
      "beacons":[
         {
            "bid":1,
            "rssi":-83
         },
         {
            "bid":2,
            "rssi":-76
         },
         {
            "bid":3,
            "rssi":-78
         },
         {
            "bid":4,
            "rssi":-80
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-85
         }
      ]
   },
   {
      "x":156,
      "y":120,
      "beacons":[
         {
            "bid":1,
            "rssi":-84
         },
         {
            "bid":2,
            "rssi":-76
         },
         {
            "bid":3,
            "rssi":-85
         },
         {
            "bid":4,
            "rssi":-78
         },
         {
            "bid":5,
            "rssi":-71
         },
         {
            "bid":6,
            "rssi":-83
         }
      ]
   },
   {
      "x":156,
      "y":160,
      "beacons":[
         {
            "bid":1,
            "rssi":-82
         },
         {
            "bid":2,
            "rssi":-72
         },
         {
            "bid":3,
            "rssi":-76
         },
         {
            "bid":4,
            "rssi":-77
         },
         {
            "bid":5,
            "rssi":-71
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":156,
      "y":200,
      "beacons":[
         {
            "bid":1,
            "rssi":-88
         },
         {
            "bid":2,
            "rssi":-78
         },
         {
            "bid":3,
            "rssi":-76
         },
         {
            "bid":4,
            "rssi":-88
         },
         {
            "bid":5,
            "rssi":-70
         },
         {
            "bid":6,
            "rssi":-83
         }
      ]
   },
   {
      "x":156,
      "y":240,
      "beacons":[
         {
            "bid":1,
            "rssi":-84
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-75
         },
         {
            "bid":4,
            "rssi":-81
         },
         {
            "bid":5,
            "rssi":-71
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":156,
      "y":280,
      "beacons":[
         {
            "bid":1,
            "rssi":-85
         },
         {
            "bid":2,
            "rssi":-75
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-81
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-72
         }
      ]
   },
   {
      "x":156,
      "y":320,
      "beacons":[
         {
            "bid":1,
            "rssi":-88
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-74
         },
         {
            "bid":4,
            "rssi":-85
         },
         {
            "bid":5,
            "rssi":-76
         },
         {
            "bid":6,
            "rssi":-77
         }
      ]
   },
   {
      "x":289,
      "y":40,
      "beacons":[
         {
            "bid":1,
            "rssi":-82
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-75
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-85
         }
      ]
   },
   {
      "x":289,
      "y":80,
      "beacons":[
         {
            "bid":1,
            "rssi":-80
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-76
         },
         {
            "bid":5,
            "rssi":-68
         },
         {
            "bid":6,
            "rssi":-80
         }
      ]
   },
   {
      "x":289,
      "y":120,
      "beacons":[
         {
            "bid":1,
            "rssi":-89
         },
         {
            "bid":2,
            "rssi":-78
         },
         {
            "bid":3,
            "rssi":-76
         },
         {
            "bid":4,
            "rssi":-80
         },
         {
            "bid":5,
            "rssi":-72
         },
         {
            "bid":6,
            "rssi":-83
         }
      ]
   },
   {
      "x":289,
      "y":160,
      "beacons":[
         {
            "bid":1,
            "rssi":-89
         },
         {
            "bid":2,
            "rssi":-85
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-79
         },
         {
            "bid":5,
            "rssi":-74
         },
         {
            "bid":6,
            "rssi":-74
         }
      ]
   },
   {
      "x":289,
      "y":200,
      "beacons":[
         {
            "bid":1,
            "rssi":-87
         },
         {
            "bid":2,
            "rssi":-82
         },
         {
            "bid":3,
            "rssi":-75
         },
         {
            "bid":4,
            "rssi":-78
         },
         {
            "bid":5,
            "rssi":-73
         },
         {
            "bid":6,
            "rssi":-75
         }
      ]
   },
   {
      "x":289,
      "y":240,
      "beacons":[
         {
            "bid":1,
            "rssi":-91
         },
         {
            "bid":2,
            "rssi":-85
         },
         {
            "bid":3,
            "rssi":-76
         },
         {
            "bid":4,
            "rssi":-73
         },
         {
            "bid":5,
            "rssi":-71
         },
         {
            "bid":6,
            "rssi":-76
         }
      ]
   },
   {
      "x":289,
      "y":280,
      "beacons":[
         {
            "bid":1,
            "rssi":-86
         },
         {
            "bid":2,
            "rssi":-86
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-80
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-80
         }
      ]
   },
   {
      "x":289,
      "y":320,
      "beacons":[
         {
            "bid":1,
            "rssi":-89
         },
         {
            "bid":2,
            "rssi":-82
         },
         {
            "bid":3,
            "rssi":-83
         },
         {
            "bid":4,
            "rssi":-88
         },
         {
            "bid":5,
            "rssi":-79
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   }
];
