var test_data = [
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-91
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-88
         },
         {
            "bid":5,
            "rssi":-85
         },
         {
            "bid":6,
            "rssi":-79
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-94
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-90
         },
         {
            "bid":5,
            "rssi":-83
         },
         {
            "bid":6,
            "rssi":-79
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-96
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-90
         },
         {
            "bid":5,
            "rssi":-85
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-97
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-91
         },
         {
            "bid":5,
            "rssi":-82
         },
         {
            "bid":6,
            "rssi":-77
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-94
         },
         {
            "bid":2,
            "rssi":-77
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-91
         },
         {
            "bid":5,
            "rssi":-80
         },
         {
            "bid":6,
            "rssi":-77
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-93
         },
         {
            "bid":2,
            "rssi":-77
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-89
         },
         {
            "bid":5,
            "rssi":-76
         },
         {
            "bid":6,
            "rssi":-80
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-90
         },
         {
            "bid":2,
            "rssi":-77
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-86
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-81
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-87
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-83
         },
         {
            "bid":4,
            "rssi":-85
         },
         {
            "bid":5,
            "rssi":-74
         },
         {
            "bid":6,
            "rssi":-84
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-85
         },
         {
            "bid":2,
            "rssi":-78
         },
         {
            "bid":3,
            "rssi":-82
         },
         {
            "bid":4,
            "rssi":-85
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-83
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-85
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-81
         },
         {
            "bid":5,
            "rssi":-70
         },
         {
            "bid":6,
            "rssi":-82
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-85
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-78
         },
         {
            "bid":5,
            "rssi":-70
         },
         {
            "bid":6,
            "rssi":-83
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-85
         },
         {
            "bid":2,
            "rssi":-78
         },
         {
            "bid":3,
            "rssi":-78
         },
         {
            "bid":4,
            "rssi":-76
         },
         {
            "bid":5,
            "rssi":-68
         },
         {
            "bid":6,
            "rssi":-84
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-83
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-76
         },
         {
            "bid":5,
            "rssi":-70
         },
         {
            "bid":6,
            "rssi":-84
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-83
         },
         {
            "bid":2,
            "rssi":-78
         },
         {
            "bid":3,
            "rssi":-78
         },
         {
            "bid":4,
            "rssi":-73
         },
         {
            "bid":5,
            "rssi":-73
         },
         {
            "bid":6,
            "rssi":-88
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-85
         },
         {
            "bid":2,
            "rssi":-81
         },
         {
            "bid":3,
            "rssi":-78
         },
         {
            "bid":4,
            "rssi":-73
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-86
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-87
         },
         {
            "bid":2,
            "rssi":-81
         },
         {
            "bid":3,
            "rssi":-82
         },
         {
            "bid":4,
            "rssi":-71
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-89
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-86
         },
         {
            "bid":2,
            "rssi":-82
         },
         {
            "bid":3,
            "rssi":-83
         },
         {
            "bid":4,
            "rssi":-71
         },
         {
            "bid":5,
            "rssi":-77
         },
         {
            "bid":6,
            "rssi":-91
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-85
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-82
         },
         {
            "bid":4,
            "rssi":-75
         },
         {
            "bid":5,
            "rssi":-78
         },
         {
            "bid":6,
            "rssi":-90
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-83
         },
         {
            "bid":2,
            "rssi":-81
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-78
         },
         {
            "bid":5,
            "rssi":-80
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-81
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-77
         },
         {
            "bid":5,
            "rssi":-81
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-79
         },
         {
            "bid":2,
            "rssi":-78
         },
         {
            "bid":3,
            "rssi":-78
         },
         {
            "bid":4,
            "rssi":-77
         },
         {
            "bid":5,
            "rssi":-80
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-78
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-75
         },
         {
            "bid":5,
            "rssi":-80
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-81
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-75
         },
         {
            "bid":5,
            "rssi":-80
         },
         {
            "bid":6,
            "rssi":-88
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-78
         },
         {
            "bid":2,
            "rssi":-83
         },
         {
            "bid":3,
            "rssi":-83
         },
         {
            "bid":4,
            "rssi":-75
         },
         {
            "bid":5,
            "rssi":-80
         },
         {
            "bid":6,
            "rssi":-89
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-75
         },
         {
            "bid":2,
            "rssi":-82
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-75
         },
         {
            "bid":5,
            "rssi":-77
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-75
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-75
         },
         {
            "bid":5,
            "rssi":-74
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-77
         },
         {
            "bid":2,
            "rssi":-76
         },
         {
            "bid":3,
            "rssi":-82
         },
         {
            "bid":4,
            "rssi":-76
         },
         {
            "bid":5,
            "rssi":-72
         },
         {
            "bid":6,
            "rssi":-84
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-77
         },
         {
            "bid":2,
            "rssi":-77
         },
         {
            "bid":3,
            "rssi":-82
         },
         {
            "bid":4,
            "rssi":-76
         },
         {
            "bid":5,
            "rssi":-74
         },
         {
            "bid":6,
            "rssi":-82
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-81
         },
         {
            "bid":2,
            "rssi":-77
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-76
         },
         {
            "bid":5,
            "rssi":-78
         },
         {
            "bid":6,
            "rssi":-82
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-83
         },
         {
            "bid":2,
            "rssi":-76
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-78
         },
         {
            "bid":5,
            "rssi":-78
         },
         {
            "bid":6,
            "rssi":-80
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-85
         },
         {
            "bid":2,
            "rssi":-72
         },
         {
            "bid":3,
            "rssi":-77
         },
         {
            "bid":4,
            "rssi":-80
         },
         {
            "bid":5,
            "rssi":-77
         },
         {
            "bid":6,
            "rssi":-79
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-87
         },
         {
            "bid":2,
            "rssi":-70
         },
         {
            "bid":3,
            "rssi":-78
         },
         {
            "bid":4,
            "rssi":-82
         },
         {
            "bid":5,
            "rssi":-73
         },
         {
            "bid":6,
            "rssi":-79
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-90
         },
         {
            "bid":2,
            "rssi":-70
         },
         {
            "bid":3,
            "rssi":-76
         },
         {
            "bid":4,
            "rssi":-87
         },
         {
            "bid":5,
            "rssi":-72
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-91
         },
         {
            "bid":2,
            "rssi":-74
         },
         {
            "bid":3,
            "rssi":-75
         },
         {
            "bid":4,
            "rssi":-88
         },
         {
            "bid":5,
            "rssi":-71
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-90
         },
         {
            "bid":2,
            "rssi":-76
         },
         {
            "bid":3,
            "rssi":-72
         },
         {
            "bid":4,
            "rssi":-89
         },
         {
            "bid":5,
            "rssi":-70
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-93
         },
         {
            "bid":2,
            "rssi":-78
         },
         {
            "bid":3,
            "rssi":-71
         },
         {
            "bid":4,
            "rssi":-89
         },
         {
            "bid":5,
            "rssi":-76
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-94
         },
         {
            "bid":2,
            "rssi":-81
         },
         {
            "bid":3,
            "rssi":-74
         },
         {
            "bid":4,
            "rssi":-91
         },
         {
            "bid":5,
            "rssi":-78
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-93
         },
         {
            "bid":2,
            "rssi":-82
         },
         {
            "bid":3,
            "rssi":-73
         },
         {
            "bid":4,
            "rssi":-91
         },
         {
            "bid":5,
            "rssi":-80
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-92
         },
         {
            "bid":2,
            "rssi":-83
         },
         {
            "bid":3,
            "rssi":-76
         },
         {
            "bid":4,
            "rssi":-91
         },
         {
            "bid":5,
            "rssi":-76
         },
         {
            "bid":6,
            "rssi":-77
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-91
         },
         {
            "bid":2,
            "rssi":-83
         },
         {
            "bid":3,
            "rssi":-78
         },
         {
            "bid":4,
            "rssi":-87
         },
         {
            "bid":5,
            "rssi":-76
         },
         {
            "bid":6,
            "rssi":-74
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-93
         },
         {
            "bid":2,
            "rssi":-82
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-86
         },
         {
            "bid":5,
            "rssi":-76
         },
         {
            "bid":6,
            "rssi":-73
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-92
         },
         {
            "bid":2,
            "rssi":-86
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-90
         },
         {
            "bid":5,
            "rssi":-83
         },
         {
            "bid":6,
            "rssi":-74
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-95
         },
         {
            "bid":2,
            "rssi":-89
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-90
         },
         {
            "bid":5,
            "rssi":-80
         },
         {
            "bid":6,
            "rssi":-76
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-96
         },
         {
            "bid":2,
            "rssi":-88
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-90
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-78
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-96
         },
         {
            "bid":2,
            "rssi":-84
         },
         {
            "bid":3,
            "rssi":-77
         },
         {
            "bid":4,
            "rssi":-88
         },
         {
            "bid":5,
            "rssi":-72
         },
         {
            "bid":6,
            "rssi":-83
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-97
         },
         {
            "bid":2,
            "rssi":-81
         },
         {
            "bid":3,
            "rssi":-75
         },
         {
            "bid":4,
            "rssi":-86
         },
         {
            "bid":5,
            "rssi":-73
         },
         {
            "bid":6,
            "rssi":-82
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-97
         },
         {
            "bid":2,
            "rssi":-81
         },
         {
            "bid":3,
            "rssi":-75
         },
         {
            "bid":4,
            "rssi":-85
         },
         {
            "bid":5,
            "rssi":-72
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-97
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-77
         },
         {
            "bid":4,
            "rssi":-84
         },
         {
            "bid":5,
            "rssi":-73
         },
         {
            "bid":6,
            "rssi":-87
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-94
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-83
         },
         {
            "bid":5,
            "rssi":-75
         },
         {
            "bid":6,
            "rssi":-81
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-95
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-84
         },
         {
            "bid":4,
            "rssi":-84
         },
         {
            "bid":5,
            "rssi":-76
         },
         {
            "bid":6,
            "rssi":-77
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-96
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-85
         },
         {
            "bid":4,
            "rssi":-85
         },
         {
            "bid":5,
            "rssi":-79
         },
         {
            "bid":6,
            "rssi":-76
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-96
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-87
         },
         {
            "bid":4,
            "rssi":-85
         },
         {
            "bid":5,
            "rssi":-81
         },
         {
            "bid":6,
            "rssi":-74
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-97
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-87
         },
         {
            "bid":4,
            "rssi":-87
         },
         {
            "bid":5,
            "rssi":-79
         },
         {
            "bid":6,
            "rssi":-73
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-98
         },
         {
            "bid":2,
            "rssi":-80
         },
         {
            "bid":3,
            "rssi":-81
         },
         {
            "bid":4,
            "rssi":-88
         },
         {
            "bid":5,
            "rssi":-76
         },
         {
            "bid":6,
            "rssi":-72
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-98
         },
         {
            "bid":2,
            "rssi":-82
         },
         {
            "bid":3,
            "rssi":-78
         },
         {
            "bid":4,
            "rssi":-90
         },
         {
            "bid":5,
            "rssi":-73
         },
         {
            "bid":6,
            "rssi":-72
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-98
         },
         {
            "bid":2,
            "rssi":-81
         },
         {
            "bid":3,
            "rssi":-76
         },
         {
            "bid":4,
            "rssi":-92
         },
         {
            "bid":5,
            "rssi":-73
         },
         {
            "bid":6,
            "rssi":-73
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-98
         },
         {
            "bid":2,
            "rssi":-79
         },
         {
            "bid":3,
            "rssi":-77
         },
         {
            "bid":4,
            "rssi":-94
         },
         {
            "bid":5,
            "rssi":-73
         },
         {
            "bid":6,
            "rssi":-71
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-98
         },
         {
            "bid":2,
            "rssi":-78
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-95
         },
         {
            "bid":5,
            "rssi":-74
         },
         {
            "bid":6,
            "rssi":-70
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-98
         },
         {
            "bid":2,
            "rssi":-77
         },
         {
            "bid":3,
            "rssi":-79
         },
         {
            "bid":4,
            "rssi":-94
         },
         {
            "bid":5,
            "rssi":-77
         },
         {
            "bid":6,
            "rssi":-71
         }
      ]
   },
   {
      "x":0,
      "y":0,
      "beacons":[
         {
            "bid":1,
            "rssi":-98
         },
         {
            "bid":2,
            "rssi":-77
         },
         {
            "bid":3,
            "rssi":-80
         },
         {
            "bid":4,
            "rssi":-92
         },
         {
            "bid":5,
            "rssi":-81
         },
         {
            "bid":6,
            "rssi":-72
         }
      ]
   }
];
